### ISSUE TITLE
What makes sltbench better?

### ISSUE THREAD

**Issue by nevion** [ivafanas/sltbench#63]
From reddit , ~1 year ago:

> I've been working on this tool for a long time, and now it looks ready to be published.
> 
> The key features of sltbench:
> 
> It is significantly faster than the most wide-spread analogue googlebench (4.7x times for testing dataset). This feature leads to less machine time wasted for performance testing.
> 
> It produces results with less relative error (3% vs 15% for testing dataset). That leads to less false positives and negatives.

The readme also stated:

>4.7x times speedup sounds extremely effective for projects where performance is super critical, tested meticulously and benchmarking takes about several hours or even days (for our project it was about a week).

What circumstances and differences lead to a 4.7x time difference for benchmarking vs google benchmark?

Also - why is the relative error lower?

**Comment by ivafanas** [comment]
Measure algorithm.

Google benchmark uses average execution time. Sltbench uses "reproducible minimum" execution time and stops ASAP.

I would suggest to compare google benchmark and sltbench for the small set of the most important functions in your project before choosing framework. Sltbench might be better in some way but googlebench has strong community.

**Comment by nevion** [comment]
Is there a paper explaining this estimation algorithm as pertains to benchmarking?

**Comment by ivafanas** [comment]
No, there is no a paper.

**Comment by ivafanas** [comment]
It is something about: "run benchmark 4 times, look for max deviation".

You can find documentation about metrics here:
https://github.com/ivafanas/sltbench/tree/master/tools/metrics
(this link is given right in the [main README](https://github.com/ivafanas/sltbench/blob/master/README.md))

Testing procedure:
https://github.com/ivafanas/sltbench/blob/master/tools/metrics/benchbench/impl/benchcc.py#L94

Statistics collection:
https://github.com/ivafanas/sltbench/blob/master/tools/metrics/benchbench/impl/benchcc.py#L57

Default options:
https://github.com/ivafanas/sltbench/blob/master/tools/metrics/benchbench/main.py#L11

How-to-measure documentation:
https://github.com/ivafanas/sltbench/blob/master/doc/howtobenchmark.md
