### ISSUE TITLE
Add error bars on time, not just overall result

### ISSUE THREAD

**Issue by alexeyr** [ivafanas/sltbench#69]
`ok`/`IMPRECISE` already serves as a kind of error measure, but with very little granularity. Though maybe it isn't worth it compared to nonius because sltbench executes benchmarks many fewer times?

**Comment by ivafanas** [comment]
`sltbench` searches for a some kind of "the most popular minimum". It is either found either not.

This logic performs an attempt to remove "illegal" measurements results. It is unclear how to measure errors. Is it a difference between minimum and maximum including "illegal" results?

**Comment by alexeyr** [comment]
OK, thank you.
